# Generated by Django 4.2.27 on 2026-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('middleName', models.CharField(blank=True, max_length=128, null=True)),
                ('lastName', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employeeImages/')),
                ('mobileNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('emailAddress', models.EmailField(max_length=254, unique=True)),
                ('designation', models.CharField(choices=[('Associate Software Engineer', 'Associate Software Engineer'), ('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Staff Software Engineer', 'Staff Software Engineer'), ('Senior Staff', 'Senior Staff'), ('Principal Engineer', 'Principal Engineer'), ('Senior Principal Engineer', 'Senior Principal Engineer'), ('Distinguished Engineer', 'Distinguished Engineer')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
