# Generated by Django 4.2.27 on 2026-01-10 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='dateOfJoining',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
